pr: none
trigger: none

variables:
- group: devopsforai-aml-vg

stages:
- stage: 'Dev'
  displayName: 'Dev'
  jobs:
  - job: "Provision_Dev"
    displayName: "Provision Dev resources"
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 0
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'AzureResourceConnection'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(RESOURCE_GROUP)'
        location: $(LOCATION)
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/environment_setup/arm-templates/cloud-di-environment.json'
        overrideParameters: '-location $(LOCATION) -dbWorkspace $(DATABRICKS_WS_NAME)'
        deploymentMode: 'Incremental'
      displayName: 'Deploy OH resources to Azure'
    - task: AzurePowerShell@4
      displayName: 'Create ADF Workspace'
      inputs:
        azureSubscription: 'AzureResourceConnection'
        ScriptPath: '$(Build.SourcesDirectory)/adf/utils/New-DataFactory.ps1'
        ScriptArguments: '-ResourceGroupName $(RESOURCE_GROUP) -DataFactoryName $(DATA_FACTORY_NAME) -Location $(LOCATION)'
        azurePowerShellVersion: LatestVersion


  